### ISSUE TITLE
Required validator fails, even when a value is provided.

### ISSUE THREAD

**Issue by ericrini** [Aldaviva/mongoose-moment#4] opened 2016-07-25 14:55 UTC
If I define a schema like this.

```
mongoose.schema({
    "occurredAt": {
        "type": "Moment",
        "required": true
    }
});
```

Mongoose throws a ValidatorError llike this.

```
{
    "occurredAt": {
        "message": "Path `occurredAt` is required.",
        "name": "ValidatorError",
        "properties": {
            "type": "required",
            "message": "Path `{PATH}` is required.",
            "path": "occurredAt",
            "value": 1472116740000
        },
        "kind": "required",
        "path": "occurredAt",
        "value": 1472116740000
    }
}
```

Note that the error specifically indicates that `value": 1472116740000` was present, even though it is throwing a ValidatorError. This is strange behavior that goes away when I change the type of the property from "Moment" to some other thing.

**Comment by MikiDi** [comment] 2016-09-06 15:15
I am experiencing the same issue as @ericrini: mongoose validation fails on the value of a property with type "Moment" for no obvious reason.
In my case saving a freshly created object (with moment property set) works, although when fetching the object, modifying the property with type "Moment" and then trying to save fails.

**Comment by MikiDi** [comment] 2016-09-07 14:24
I have added some tests in my fork (["bugfix"-branch](https://github.com/MikiDi/mongoose-moment/tree/bugfix)) to illustrate the problem. As far as I can see the error occurs on the property that has the option `{required: true}` when updating a schema that has multiple `'Moment'`-properties in it.

example of schema that fails to update:

``` Javascript
schema = new Schema({
  n: 'Moment',
  m: {type: 'Moment', required: true},
  docs: [{ m: 'Moment' }]
});
```

any idea's on where I should start looking? @Aldaviva @gastonelhordoy @brad-decker

**Comment by Aldaviva** [comment] 2016-10-16 04:44
I'm having trouble reproducing this issue. Here's what I've tried so far:
- `mongoose-moment` 0.0.1, 0.1.1
- `mongoose` 3.8.22, 4.6.3
- `moment` 2.9.0, 2.15.1
- `node-mongodb-native` 1.4.30
- MongoDB 2.4.14
- schema with multiple required Moment fields

I am able to save documents to the database without validation errors appearing, and the documents show up in Mongo correctly.

**Which versions of these libraries are giving you errors?**

Thanks.

**Comment by MikiDi** [comment] 2016-10-27 14:52
Hi,  
Thanks for your time & effort in investigating this bug.  
Did you try to run the mocha-tests (`npm test`) I wrote in addition to the existing ones? ([https://github.com/MikiDi/mongoose-moment/tree/bugfix](https://github.com/MikiDi/mongoose-moment/tree/bugfix)), the last test is the one that fails. Please note that **saving the first time is not a problem, updating is**.

schema that **fails** to update:

``` javascript
new Schema({
          n: 'Moment',
          m: {type: 'Moment', required: true},
          docs: [{ m: 'Moment' }]
});
```

schema that **succeeds** to update:

``` javascript
new Schema({
          m: {type: 'Moment', required: true},
          docs: [{ m: 'Moment' }]
      });
```

package versions:
- mongoose-moment@0.1.1
- mongoose@4.6.0
- moment@2.14.1

stacktrace:

```
  ValidationError: Path `m` is required.
      at MongooseError.ValidationError (node_modules/mongoose/lib/error/validation.js:22:11)
      at model.Document.invalidate (node_modules/mongoose/lib/document.js:1410:32)
      at node_modules/mongoose/lib/document.js:1286:17
      at validate (node_modules/mongoose/lib/schematype.js:705:7)
      at node_modules/mongoose/lib/schematype.js:742:9
      at Array.forEach (native)
      at SchemaMoment.SchemaType.doValidate (node_modules/mongoose/lib/schematype.js:710:19)
      at node_modules/mongoose/lib/document.js:1284:9
```

The validator complains that the path (``m`` in this case) is not present although it definitely is, as mentioned in previous comments by @ericrini  and myself.

I admit that it's kind of hard to reproduce & figure out the root cause ... in the tests I tried to narrow down the issue the best I could, I hope this will help.  
Thanks,  
M.

**Comment by Aldaviva** [comment] 2016-10-28 09:54
Thanks for the additional info and clarifications! I will try your bugfix branch with the failing test case.

**Comment by Aldaviva** [comment] 2016-10-29 08:47
Doing some debugging now.

**Comment by Aldaviva** [comment] 2016-11-16 08:17
I've committed a change to my own [bugfix branch](https://github.com/Aldaviva/mongoose-moment/commits/bugfix) and all tests are passing.

Here's what I found was happening:
1. In the failing test case `with normal property and required property`, the optional property `n` is updated with a different Moment value.
2. Mongoose validates the document when the document is saved.
3. The `m` field is required, but its Moment value has not changed. When Mongoose validates the value of `m`, it doesn't read the parsed Moment value, it instead reads the serialized numeric millisecond value from the document's raw storage.
4. Numeric values fail the `Moment.isMoment()` check in our `SchemaMoment.prototype.checkRequired()`, so the document is invalid.

Here's what I've done to make the tests pass:
- changed `SchemaMoment.prototype.checkRequired()` to allow _either_ valid Moments _or_ numeric values.
- added a test that verifies that you can set a field of type Moment to have a numeric value, and our schema will correctly parse the millisecond timestamp into a Moment instance.

I think this is a good approach because I looked at a few official and third-party Mongoose schema types and they generally just perform simple null checks for `checkRequired()`, as opposed to performing complex validation logic to make sure the value is allowed.

**Comment by MikiDi** [comment] 2017-01-04 17:01
I haven't come across any issues any more since using this patch ... this can be merged I guess :-)  
Thanks @Aldaviva

**Comment by Aldaviva** [comment] 2017-01-09 10:48
Cool, thanks. I'll work on getting this merged, version bumped, and published.

**Comment by Aldaviva** [comment] 2017-01-11 06:56
The fix has been merged into master and published on [npm](https://www.npmjs.com/package/mongoose-moment) as `mongoose-moment@0.1.2`.

Thanks for all your help, @ericrini and @MikiDi! :smile:

**Closed as completed by Aldaviva** 2017-01-11 06:56 UTC
